### ISSUE TITLE
[BUG] ReferenceError: React is not defined

### ISSUE THREAD

**Issue by ramrami-B** [moofarm/ssuckssuck-frontend#1]
## 🐛 Bug Issue
스토리북에서 아래 에러 발생 (src/stories/Button.jsx, Header.jsx, Page.jsx)
```
ReferenceError: React is not defined
    at Page (http://localhost:6006/stories-Page-stories.c191e4182a2faa4485a8.hot-update.js:69:5)
    at renderWithHooks (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:46339:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:50103:13)
    at beginWork (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:51616:16)
    at beginWork$1 (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:57455:14)
    at performUnitOfWork (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:56589:12)
    at workLoopSync (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:56495:5)
    at renderRootSync (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:56463:7)
    at recoverFromConcurrentError (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:55879:20)
    at performConcurrentWorkOnRoot (http://localhost:6006/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2b1b68.iframe.bundle.js:55779:22)
```

**Comment by ramrami-B** [comment]
## 👏🏻 Solution
react17부터는 import React from “react” 구문을 생략 할 수 있기 때문에 이전 커밋에서 생략 했는데
src/stories 내부의 jsx 파일에는 react를 import 해줘야 해서 발생한 오류였다!
오류가 나는 파일에 import 문 추가해서 해결

**Comment by ramrami-B** [comment]
2073a249c58af48633865297a0513db87badb23b
